# .github/workflows/build.yml

name: Build Linux Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CMAKE_BUILD_TYPE: Release
  CCACHE_MAXSIZE: 200M

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Install build tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -y -qq install build-essential cmake ninja-build ccache libssl-dev
        ccache --max-size=$CCACHE_MAXSIZE
        ccache -z

    - uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
          build
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.cpp', '**/*.hpp', '**/CMakeLists.txt', '**/*.cmake', 'extern/DPP/**') }}
        restore-keys: ${{ runner.os }}-ccache-

    - name: Configure & build
      run: |
        cmake -S . -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build --target AurebeshDroid --parallel $(nproc)

    - name: Show ccache stats
      if: always()
      run: ccache -s

    - uses: actions/upload-artifact@v4
      with:
        name: AurebeshDroid
        path: |
          build/AurebeshDroid