# .github/workflows/build.yml

name: Build & Release Aurebesh Droid (Linux)

on:
  push:
    tags:
      - "v*.*.*" 

env:
  CMAKE_BUILD_TYPE: Release
  CCACHE_MAXSIZE: 200M
  BUILD_DIR: build

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build tools
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -qq install \
            build-essential cmake ninja-build ccache libssl-dev pkg-config jq
          ccache --max-size=$CCACHE_MAXSIZE
          ccache -z

      - uses: actions/cache@v3
        with:
          path: |
            ~/.ccache
            ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.cpp', '**/*.hpp', '**/CMakeLists.txt', '**/*.cmake', 'extern/DPP/**') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Configure & build
        run: |
          cmake -S . -B $BUILD_DIR -G Ninja \
                -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build $BUILD_DIR --target AurebeshDroid --parallel $(nproc)

      - name: Verify binary
        run: |
          ls -lh $BUILD_DIR/AurebeshDroid
          file $BUILD_DIR/AurebeshDroid
          test -x $BUILD_DIR/AurebeshDroid

      - name: Rename to Release asset name
        run: |
          mv $BUILD_DIR/AurebeshDroid $BUILD_DIR/LinuxBinary

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ${{ env.BUILD_DIR }}/LinuxBinary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show ccache stats
        if: always()
        run: ccache -s
