# .github/workflows/build.yml

name: Build & Release Aurebesh Droid (Linux)

on:
  push:
    branches: [ main ]   # <- release on every push to main

env:
  CMAKE_BUILD_TYPE: Release
  CCACHE_MAXSIZE: 200M
  BUILD_DIR: build

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build tools
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -qq install \
            build-essential cmake ninja-build ccache libssl-dev pkg-config
          ccache --max-size=$CCACHE_MAXSIZE
          ccache -z

      - uses: actions/cache@v3
        with:
          path: |
            ~/.ccache
            ${{ env.BUILD_DIR }}
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.cpp', '**/*.hpp', '**/CMakeLists.txt', '**/*.cmake', 'extern/DPP/**') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Configure & build
        run: |
          cmake -S . -B $BUILD_DIR -G Ninja \
                -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build $BUILD_DIR --target AurebeshDroid --parallel $(nproc)

      - name: Verify binary
        run: |
          ls -lh $BUILD_DIR/AurebeshDroid
          file $BUILD_DIR/AurebeshDroid
          test -x $BUILD_DIR/AurebeshDroid

      - name: Rename to Release asset name
        run: mv $BUILD_DIR/AurebeshDroid $BUILD_DIR/LinuxBinary

      - name: Create/Update "nightly" GitHub Release (mark as latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly                 # fixed tag that we reuse
          name: Nightly                    # release name
          make_latest: true                # mark this as the "latest" release
          draft: false
          prerelease: false
          files: ${{ env.BUILD_DIR }}/LinuxBinary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show ccache stats
        if: always()
        run: ccache -s

      - name: Restart Heroku dynos
        if: always()
        run: |
          curl -X DELETE "https://api.heroku.com/apps/${HEROKU_APP_NAME}/dynos" \
            -H "Accept: application/vnd.heroku+json; version=3" \
            -H "Authorization: Bearer ${HEROKU_API_KEY}"
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}